server:
  port: 8899
  address: 0.0.0.0
  servlet:
    context-path: /

shenyu:
  register:
    register-type: http #zookeeper #etcd #nacos #consul
    serverLists: http://localhost:9095 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: admin
      password: 123456
  sdk:
    enabled: true
    register-type: local
    server-lists: http://localhost:9195
